{- https://www.nomadproject.io/docs/configuration -}
let Map = (../Prelude.dhall).Map.Type
let AgentPort = ./AgentPort.dhall
let Plugin = ./Plugin.dhall
in { -- acl : Optional ACL -- Specifies configuration which is specific to ACLs.
   --, addresses : Optional Addresses -- Specifies the bind address for individual network services. Any values configured in this stanza take precedence over the default bind_addr. These values should be specified in IP format without a port (ex. "0.0.0.0"). To set the port, see the ports field. The values support go-sockaddr/template format.
   --, advertise : Optional Advertise -- Specifies the advertise address for individual network services. This can be used to advertise a different address to the peers of a server or a client node to support more complex network configurations such as NAT. This configuration is optional, and defaults to the bind address of the specific network service if it is not provided. Any values configured in this stanza take precedence over the default bind_addr.
   --, audit : Optional Audit -- Enterprise-only. Specifies audit logging configuration.
     bind_addr : Optional Text -- Specifies which address the Nomad agent should bind to for network services, including the HTTP interface as well as the internal gossip protocol and RPC mechanism. This should be specified in IP format, and can be used to easily bind all network services to the same address. It is also possible to bind the individual services to different addresses using the addresses configuration option. Dev mode (-dev) defaults to localhost. The value supports go-sockaddr/template format.
   --, client : Optional Client -- Specifies configuration which is specific to the Nomad client.
   --, consul : Optional Consul -- Specifies configuration for connecting to Consul.
   , datacenter : Optional Text -- Specifies the data center of the local agent. All members of a datacenter should share a local LAN connection.
   , data_dir : Text -- Specifies a local directory used to store agent state. Client nodes use this directory by default to store temporary allocation data as well as cluster information. Server nodes use this directory to store cluster state, including the replicated log and snapshot data. This must be specified as an absolute path.
   , disable_anonymous_signature : Optional Bool -- (bool: false) -- Specifies if Nomad should provide an anonymous signature for de-duplication with the update check.
   , disable_update_check : Optional Bool -- (bool: false) -- Specifies if Nomad should not check for updates and security bulletins. This defaults to true in Nomad Enterprise.
   , enable_debug : Optional Bool -- (bool: false) -- Specifies if the debugging HTTP endpoints should be enabled. These endpoints can be used with profiling tools to dump diagnostic information about Nomad's internals.
   , enable_syslog : Optional Bool -- (bool: false) -- Specifies if the agent should log to syslog. This option only works on Unix based systems.
   , http_api_response_headers : Optional (Map Text Text) -- Specifies user-defined headers to add to the HTTP API responses.
   , leave_on_interrupt : Optional Bool -- (bool: false) -- Specifies if the agent should gracefully leave when receiving the interrupt signal. By default, the agent will exit forcefully on any signal. This value should only be set to true on server agents if it is expected that a terminated server instance will never join the cluster again.
   , leave_on_terminate : Optional Bool -- (bool: false) -- Specifies if the agent should gracefully leave when receiving the terminate signal. By default, the agent will exit forcefully on any signal. This value should only be set to true on server agents if it is expected that a terminated server instance will never join the cluster again.
   , https_handshake_timeout : Optional Text -- Configures the limit for how long the HTTPS server in both client and server agents will wait for a client to complete a TLS handshake. This should be kept conservative as it limits how many connections an unauthenticated attacker can open if tls.http = true is being used (strongly recommended in production). Default value is 5s. 0 disables HTTP handshake timeouts.
   , http_max_conns_per_client : Optional Natural -- Configures a limit of how many concurrent TCP connections a single client IP address is allowed to open to the agent's HTTP server. This affects the HTTP servers in both client and server agents. Default value is 100. 0 disables HTTP connection limits.
   , rpc_handshake_timeout : Optional Text -- Configures the limit for how long servers will wait after a client TCP connection is established before they complete the connection handshake. When TLS is used, the same timeout applies to the TLS handshake separately from the initial protocol negotiation. All Nomad clients should perform this immediately on establishing a new connection. This should be kept conservative as it limits how many connections an unauthenticated attacker can open if TLS is being using to authenticate clients (strongly recommended in production). When tls.rpc is true on servers, this limits how long the connection and associated goroutines will be held open before the client successfully authenticates. Default value is 5s. 0 disables RPC handshake timeouts.
   , rpc_max_conns_per_client : Optional Natural -- Configures a limit of how many concurrent TCP connections a single source IP address is allowed to open to a single server. Client agents do not accept RPC TCP connections directly and therefore are not affected. It affects both clients connections and other server connections. Nomad clients multiplex many RPC calls over a single TCP connection, except for streaming endpoints such as log streaming which require their own connection when routed through servers. A server needs at least 2 TCP connections (1 Raft, 1 RPC) per peer server locally and in any federated region. Servers also need a TCP connection per routed streaming endpoint concurrently in use. Only operators use streaming endpoints; as of 0.10.3 Nomad client code does not. A reasonably low limit significantly reduces the ability of an unauthenticated attacker to consume unbounded resources by holding open many connections. You may need to increase this if WAN federated servers connect via proxies or NAT gateways or similar causing many legitimate connections from a single source IP. Default value is 100 which is designed to support the majority of users. 0 disables RPC connection limits. 26 is the minimum as 20 connections are always reserved for non-streaming connections (Raft and RPC) to ensure streaming RPCs do not prevent normal server operation. This minimum may be lowered in the future when streaming RPCs no longer require their own TCP connection.
   , log_level : Optional Text -- Specifies the verbosity of logs the Nomad agent will output. Valid log levels include WARN, INFO, or DEBUG in increasing order of verbosity.
   , log_json : Optional Bool -- Output logs in a JSON format.
   , log_file : Optional Text -- Specifies the path for logging. If the path does not includes a filename, the filename defaults to nomad.log. This setting can be combined with log_rotate_bytes and log_rotate_duration for a fine-grained log rotation control.
   , log_rotate_bytes : Optional Natural -- Specifies the number of bytes that should be written to a log before it needs to be rotated. Unless specified, there is no limit to the number of bytes that can be written to a log file.
   , log_rotate_duration : Optional Text -- Specifies the maximum duration a log should be written to before it needs to be rotated. Must be a duration value such as 30s.
   , log_rotate_max_files : Optional Natural -- Specifies the maximum number of older log file archives to keep, not including the log file currently being written. If set to 0 no files are ever deleted. Note that the total number of log files, for each of stderr and stdout, will be 1 greater than the log_rotate_max_files value.
   , name : Optional Text -- Specifies the name of the local node. This value is used to identify individual agents. When specified on a server, the name must be unique within the region.
   , plugin_dir : Optional Text -- Specifies the directory to use for looking up plugins. By default, this is the top-level data_dir suffixed with "plugins", like "/opt/nomad/plugins". This must be an absolute path.
   , plugin : Optional Plugin -- Specifies configuration for a specific plugin. The plugin stanza may be repeated, once for each plugin being configured. The key of the stanza is the plugin's executable name relative to the plugin_dir.
   , ports : Optional AgentPort -- Specifies the network ports used for different services required by the Nomad agent.
   , region : Optional Text -- Specifies the region the Nomad agent is a member of. A region typically maps to a geographic region, for example us, with potentially multiple zones, which map to datacenters such as us-west and us-east.
   --, sentinel : Optional Sentinel -- Specifies configuration for Sentinel policies.
   --, server : Optional Server -- Specifies configuration which is specific to the Nomad server.
   , syslog_facility : Optional Text -- Specifies the syslog facility to write to. This has no effect unless enable_syslog is true.
   --, tls : Optional TLS -- Specifies configuration for TLS.
   --, vault : Optional Vault -- Specifies configuration for connecting to Vault.
   }
